/**
 * 导入二年级下册词库到数据库
 */

const VOCAB_SEMESTER2 = {
  chinese: {
    grade2_semester2: {
      s2_lesson1: { name: "第1课 古诗二首", words: [{ text: "村庄", pinyin: "cūn zhuāng" }, { text: "居所", pinyin: "jū suǒ" }, { text: "咏柳", pinyin: "yǒng liǔ" }, { text: "碧玉", pinyin: "bì yù" }, { text: "化妆", pinyin: "huà zhuāng" }, { text: "丝绦", pinyin: "sī tāo" }, { text: "裁剪", pinyin: "cái jiǎn" }], vocabType: "poem" },
      s2_lesson2: { name: "第2课 找春天", words: [{ text: "春天", pinyin: "chūn tiān" }, { text: "寻找", pinyin: "xún zhǎo" }, { text: "姑娘", pinyin: "gū niang" }, { text: "野花", pinyin: "yě huā" }, { text: "眼睛", pinyin: "yǎn jing" }, { text: "柳枝", pinyin: "liǔ zhī" }, { text: "桃花", pinyin: "táo huā" }, { text: "杏花", pinyin: "xìng huā" }, { text: "鲜花", pinyin: "xiān huā" }, { text: "遮遮掩掩", pinyin: "zhē zhē yǎn yǎn" }, { text: "躲躲藏藏", pinyin: "duǒ duǒ cáng cáng" }, { text: "叮叮咚咚", pinyin: "dīng dīng dōng dōng" }] },
      s2_lesson3: { name: "第3课 开满鲜花的小路", words: [{ text: "鲜花", pinyin: "xiān huā" }, { text: "邮递员", pinyin: "yóu dì yuán" }, { text: "先生", pinyin: "xiān sheng" }, { text: "原来", pinyin: "yuán lái" }, { text: "大叔", pinyin: "dà shū" }, { text: "邮局", pinyin: "yóu jú" }, { text: "太太", pinyin: "tài tai" }, { text: "做客", pinyin: "zuò kè" }, { text: "惊奇", pinyin: "jīng qí" }, { text: "快活", pinyin: "kuài huo" }, { text: "美好", pinyin: "měi hǎo" }, { text: "礼物", pinyin: "lǐ wù" }] },
      s2_lesson4: { name: "第4课 邓小平爷爷植树", words: [{ text: "植树", pinyin: "zhí shù" }, { text: "碧空如洗", pinyin: "bì kōng rú xǐ" }, { text: "万里无云", pinyin: "wàn lǐ wú yún" }, { text: "公园", pinyin: "gōng yuán" }, { text: "格外", pinyin: "gé wài" }, { text: "引人注目", pinyin: "yǐn rén zhù mù" }, { text: "汗珠", pinyin: "hàn zhū" }, { text: "休息", pinyin: "xiū xi" }, { text: "柏树", pinyin: "bǎi shù" }, { text: "树苗", pinyin: "shù miáo" }, { text: "小心", pinyin: "xiǎo xīn" }, { text: "笔直", pinyin: "bǐ zhí" }] },
      s2_lesson5: { name: "第5课 雷锋叔叔，你在哪里", words: [{ text: "叔叔", pinyin: "shū shu" }, { text: "足迹", pinyin: "zú jì" }, { text: "昨天", pinyin: "zuó tiān" }, { text: "迷路", pinyin: "mí lù" }, { text: "温暖", pinyin: "wēn nuǎn" }, { text: "爱心", pinyin: "ài xīn" }, { text: "到处", pinyin: "dào chù" }, { text: "年迈", pinyin: "nián mài" }, { text: "洒下", pinyin: "sǎ xià" }, { text: "泥泞", pinyin: "ní nìng" }, { text: "晶莹", pinyin: "jīng yíng" }, { text: "寻觅", pinyin: "xún mì" }] },
      s2_lesson6: { name: "第6课 千人糕", words: [{ text: "一定", pinyin: "yí dìng" }, { text: "也许", pinyin: "yě xǔ" }, { text: "桌子", pinyin: "zhuō zi" }, { text: "平时", pinyin: "píng shí" }, { text: "难道", pinyin: "nán dào" }, { text: "味道", pinyin: "wèi dào" }, { text: "就是", pinyin: "jiù shì" }, { text: "加工", pinyin: "jiā gōng" }, { text: "农具", pinyin: "nóng jù" }, { text: "甜菜", pinyin: "tián cài" }, { text: "工具", pinyin: "gōng jù" }, { text: "劳动", pinyin: "láo dòng" }, { text: "经过", pinyin: "jīng guò" }, { text: "出色", pinyin: "chū sè" }] },
      s2_lesson7: { name: "第7课 一匹出色的马", words: [{ text: "出色", pinyin: "chū sè" }, { text: "河水", pinyin: "hé shuǐ" }, { text: "碧绿", pinyin: "bì lǜ" }, { text: "波纹", pinyin: "bō wén" }, { text: "河岸", pinyin: "hé àn" }, { text: "柳叶", pinyin: "liǔ yè" }, { text: "景色", pinyin: "jǐng sè" }, { text: "恋恋不舍", pinyin: "liàn liàn bù shě" }, { text: "柳树枝条", pinyin: "liǔ shù zhī tiáo" }, { text: "柔软", pinyin: "róu ruǎn" }, { text: "郊外", pinyin: "jiāo wài" }, { text: "跨上", pinyin: "kuà shàng" }] },
      s2_lesson8: { name: "识字1 神州谣", words: [{ text: "神州", pinyin: "shén zhōu" }, { text: "中华", pinyin: "zhōng huá" }, { text: "山川", pinyin: "shān chuān" }, { text: "黄河", pinyin: "huáng hé" }, { text: "长江", pinyin: "cháng jiāng" }, { text: "长城", pinyin: "cháng chéng" }, { text: "台湾", pinyin: "tái wān" }, { text: "海峡", pinyin: "hǎi xiá" }, { text: "民族", pinyin: "mín zú" }, { text: "奋发", pinyin: "fèn fā" }, { text: "繁荣", pinyin: "fán róng" }] },
      s2_lesson9: { name: "识字2 传统节日", words: [{ text: "节日", pinyin: "jié rì" }, { text: "春节", pinyin: "chūn jié" }, { text: "花灯", pinyin: "huā dēng" }, { text: "清明节", pinyin: "qīng míng jié" }, { text: "先人", pinyin: "xiān rén" }, { text: "龙舟", pinyin: "lóng zhōu" }, { text: "中秋", pinyin: "zhōng qiū" }, { text: "圆月", pinyin: "yuán yuè" }, { text: "转眼", pinyin: "zhuǎn yǎn" }, { text: "团圆", pinyin: "tuán yuán" }, { text: "热闹", pinyin: "rè nao" }, { text: "月饼", pinyin: "yuè bǐng" }] },
      s2_lesson10: { name: "识字3 '贝'的故事", words: [{ text: "动物", pinyin: "dòng wù" }, { text: "贝壳", pinyin: "bèi ké" }, { text: "甲骨文", pinyin: "jiǎ gǔ wén" }, { text: "张开", pinyin: "zhāng kāi" }, { text: "样子", pinyin: "yàng zi" }, { text: "可以", pinyin: "kě yǐ" }, { text: "钱币", pinyin: "qián bì" }, { text: "钱财", pinyin: "qián cái" }, { text: "有关", pinyin: "yǒu guān" }, { text: "珍贵", pinyin: "zhēn guì" }, { text: "保护", pinyin: "bǎo hù" }, { text: "损坏", pinyin: "sǔn huài" }] },
      s2_lesson11: { name: "识字4 中国美食", words: [{ text: "美食", pinyin: "měi shí" }, { text: "红烧", pinyin: "hóng shāo" }, { text: "茄子", pinyin: "qié zi" }, { text: "烤鸭", pinyin: "kǎo yā" }, { text: "羊肉", pinyin: "yáng ròu" }, { text: "蛋炒饭", pinyin: "dàn chǎo fàn" }, { text: "小鸡炖蘑菇", pinyin: "xiǎo jī dùn mó gu" }, { text: "蒸饺", pinyin: "zhēng jiǎo" }, { text: "炸酱面", pinyin: "zhá jiàng miàn" }, { text: "粥", pinyin: "zhōu" }, { text: "豆腐", pinyin: "dòu fu" }, { text: "菠菜", pinyin: "bō cài" }] },
      s2_lesson12: { name: "第8课 彩色的梦", words: [{ text: "彩色", pinyin: "cǎi sè" }, { text: "脚尖", pinyin: "jiǎo jiān" }, { text: "森林", pinyin: "sēn lín" }, { text: "雪松", pinyin: "xuě sōng" }, { text: "歌声", pinyin: "gē shēng" }, { text: "苹果", pinyin: "píng guǒ" }, { text: "精灵", pinyin: "jīng líng" }, { text: "季节", pinyin: "jì jié" }, { text: "梦境", pinyin: "mèng jìng" }, { text: "草坪", pinyin: "cǎo píng" }, { text: "葱郁", pinyin: "cōng yù" }, { text: "烟囱", pinyin: "yān cōng" }] },
      s2_lesson13: { name: "第9课 枫树上的喜鹊", words: [{ text: "喜欢", pinyin: "xǐ huan" }, { text: "好像", pinyin: "hǎo xiàng" }, { text: "说话", pinyin: "shuō huà" }, { text: "童话", pinyin: "tóng huà" }, { text: "阿姨", pinyin: "ā yí" }, { text: "对岸", pinyin: "duì àn" }, { text: "弟弟", pinyin: "dì di" }, { text: "游戏", pinyin: "yóu xì" }, { text: "发明", pinyin: "fā míng" }, { text: "字母", pinyin: "zì mǔ" }, { text: "拼音", pinyin: "pīn yīn" }, { text: "太阳伞", pinyin: "tài yáng sǎn" }] },
      s2_lesson14: { name: "第10课 沙滩上的童话", words: [{ text: "周围", pinyin: "zhōu wéi" }, { text: "补充", pinyin: "bǔ chōng" }, { text: "公主", pinyin: "gōng zhǔ" }, { text: "勇士", pinyin: "yǒng shì" }, { text: "飞机", pinyin: "fēi jī" }, { text: "地道", pinyin: "dì dào" }, { text: "火药", pinyin: "huǒ yào" }, { text: "胜利", pinyin: "shèng lì" }, { text: "叫喊", pinyin: "jiào hǎn" }, { text: "忘记", pinyin: "wàng jì" }, { text: "凶狠", pinyin: "xiōng hěn" }, { text: "商量", pinyin: "shāng liang" }] },
      s2_lesson15: { name: "第11课 我是一只小虫子", words: [{ text: "屁股", pinyin: "pì gu" }, { text: "苍耳", pinyin: "cāng ěr" }, { text: "留神", pinyin: "liú shén" }, { text: "干净", pinyin: "gān jìng" }, { text: "从来", pinyin: "cóng lái" }, { text: "幸运", pinyin: "xìng yùn" }, { text: "比如", pinyin: "bǐ rú" }, { text: "使劲", pinyin: "shǐ jìn" }, { text: "昏头昏脑", pinyin: "hūn tóu hūn nǎo" }, { text: "毛茸茸", pinyin: "máo róng róng" }, { text: "摇晃", pinyin: "yáo huàng" }, { text: "触须", pinyin: "chù xū" }] },
      s2_lesson16: { name: "第12课 寓言二则", words: [{ text: "亡羊补牢", pinyin: "wáng yáng bǔ láo" }, { text: "劝告", pinyin: "quàn gào" }, { text: "筋疲力尽", pinyin: "jīn pí lì jìn" }, { text: "明白", pinyin: "míng bai" }, { text: "图画", pinyin: "tú huà" }, { text: "老师", pinyin: "lǎo shī" }, { text: "讲桌", pinyin: "jiǎng zhuō" }, { text: "座位", pinyin: "zuò wèi" }, { text: "哈哈大笑", pinyin: "hā hā dà xiào" }, { text: "五角星", pinyin: "wǔ jiǎo xīng" }, { text: "然后", pinyin: "rán hòu" }, { text: "认真", pinyin: "rèn zhēn" }, { text: "角度", pinyin: "jiǎo dù" }, { text: "愿意", pinyin: "yuàn yì" }] },
      s2_lesson17: { name: "第13课 画杨桃", words: [{ text: "图画", pinyin: "tú huà" }, { text: "老师", pinyin: "lǎo shī" }, { text: "讲桌", pinyin: "jiǎng zhuō" }, { text: "座位", pinyin: "zuò wèi" }, { text: "哈哈大笑", pinyin: "hā hā dà xiào" }, { text: "五角星", pinyin: "wǔ jiǎo xīng" }, { text: "然后", pinyin: "rán hòu" }, { text: "认真", pinyin: "rèn zhēn" }, { text: "角度", pinyin: "jiǎo dù" }, { text: "愿意", pinyin: "yuàn yì" }, { text: "熟悉", pinyin: "shú xī" }, { text: "审视", pinyin: "shěn shì" }, { text: "半晌", pinyin: "bàn shǎng" }, { text: "和颜悦色", pinyin: "hé yán yuè sè" }] },
      s2_lesson18: { name: "第14课 小马过河", words: [{ text: "麦子", pinyin: "mài zi" }, { text: "为难", pinyin: "wéi nán" }, { text: "身边", pinyin: "shēn biān" }, { text: "四周", pinyin: "sì zhōu" }, { text: "立刻", pinyin: "lì kè" }, { text: "突然", pinyin: "tū rán" }, { text: "吃惊", pinyin: "chī jīng" }, { text: "认真", pinyin: "rèn zhēn" }, { text: "脚步", pinyin: "jiǎo bù" }, { text: "难为情", pinyin: "nán wéi qíng" }, { text: "亲切", pinyin: "qīn qiè" }, { text: "连蹦带跳", pinyin: "lián bèng dài tiào" }] },
      s2_lesson19: { name: "第15课 古诗二首", words: [{ text: "西湖", pinyin: "xī hú" }, { text: "莲叶", pinyin: "lián yè" }, { text: "无穷", pinyin: "wú qióng" }, { text: "碧绿", pinyin: "bì lǜ" }, { text: "绝句", pinyin: "jué jù" }, { text: "黄鹂", pinyin: "huáng lí" }, { text: "翠柳", pinyin: "cuì liǔ" }, { text: "白鹭", pinyin: "bái lù" }, { text: "东吴", pinyin: "dōng wú" }, { text: "含", pinyin: "hán" }, { text: "岭", pinyin: "lǐng" }, { text: "泊", pinyin: "bó" }], vocabType: "poem" },
      s2_lesson20: { name: "第16课 雷雨", words: [{ text: "雷雨", pinyin: "léi yǔ" }, { text: "乌云", pinyin: "wū yún" }, { text: "闪电", pinyin: "shǎn diàn" }, { text: "雷声", pinyin: "léi shēng" }, { text: "房子", pinyin: "fáng zi" }, { text: "窗户", pinyin: "chuāng hu" }, { text: "垂下来", pinyin: "chuí xià lái" }, { text: "迎面扑来", pinyin: "yíng miàn pū lái" }, { text: "清新", pinyin: "qīng xīn" }, { text: "越来越亮", pinyin: "yuè lái yuè liàng" }, { text: "渐渐", pinyin: "jiàn jiàn" }, { text: "黑沉沉", pinyin: "hēi chén chén" }] },
      s2_lesson21: { name: "第17课 要是你在野外迷了路", words: [{ text: "野外", pinyin: "yě wài" }, { text: "大自然", pinyin: "dà zì rán" }, { text: "天然", pinyin: "tiān rán" }, { text: "指南针", pinyin: "zhǐ nán zhēn" }, { text: "帮助", pinyin: "bāng zhù" }, { text: "向导", pinyin: "xiàng dǎo" }, { text: "指点", pinyin: "zhǐ diǎn" }, { text: "北方", pinyin: "běi fāng" }, { text: "北极星", pinyin: "běi jí xīng" }, { text: "路灯", pinyin: "lù dēng" }, { text: "永远", pinyin: "yǒng yuǎn" }, { text: "黑夜", pinyin: "hēi yè" }, { text: "特别", pinyin: "tè bié" }, { text: "积雪", pinyin: "jī xuě" }] },
      s2_lesson22: { name: "第18课 太空生活趣事多", words: [{ text: "太空", pinyin: "tài kōng" }, { text: "生活", pinyin: "shēng huó" }, { text: "宇宙", pinyin: "yǔ zhòu" }, { text: "飞船", pinyin: "fēi chuán" }, { text: "别处", pinyin: "bié chù" }, { text: "喝水", pinyin: "hē shuǐ" }, { text: "杯子", pinyin: "bēi zi" }, { text: "失去", pinyin: "shī qù" }, { text: "使用", pinyin: "shǐ yòng" }, { text: "半空", pinyin: "bàn kōng" }, { text: "容易", pinyin: "róng yì" }, { text: "浴室", pinyin: "yù shì" }, { text: "方向", pinyin: "fāng xiàng" }, { text: "安稳", pinyin: "ān wěn" }] },
      s2_lesson23: { name: "第19课 大象的耳朵", words: [{ text: "耳朵", pinyin: "ěr duo" }, { text: "扇子", pinyin: "shàn zi" }, { text: "遇到", pinyin: "yù dào" }, { text: "兔子", pinyin: "tù zi" }, { text: "后来", pinyin: "hòu lái" }, { text: "不安", pinyin: "bù ān" }, { text: "毛病", pinyin: "máo bìng" }, { text: "头痛", pinyin: "tóu tòng" }, { text: "最后", pinyin: "zuì hòu" }, { text: "人家", pinyin: "rén jia" }, { text: "耷拉", pinyin: "dā la" }, { text: "竖着", pinyin: "shù zhe" }] },
      s2_lesson24: { name: "第20课 蜘蛛开店", words: [{ text: "飞虫", pinyin: "fēi chóng" }, { text: "决定", pinyin: "jué dìng" }, { text: "商店", pinyin: "shāng diàn" }, { text: "木屋", pinyin: "mù wū" }, { text: "功夫", pinyin: "gōng fu" }, { text: "终于", pinyin: "zhōng yú" }, { text: "围巾", pinyin: "wéi jīn" }, { text: "星期", pinyin: "xīng qī" }, { text: "编织", pinyin: "biān zhī" }, { text: "口罩", pinyin: "kǒu zhào" }, { text: "长颈鹿", pinyin: "cháng jǐng lù" }, { text: "蜈蚣", pinyin: "wú gōng" }] },
      s2_lesson25: { name: "第21课 青蛙卖泥塘", words: [{ text: "青蛙", pinyin: "qīng wā" }, { text: "草籽", pinyin: "cǎo zǐ" }, { text: "野鸭", pinyin: "yě yā" }, { text: "泉水", pinyin: "quán shuǐ" }, { text: "竹子", pinyin: "zhú zi" }, { text: "应该", pinyin: "yīng gāi" }, { text: "花丛", pinyin: "huā cóng" }, { text: "尽情", pinyin: "jìn qíng" }, { text: "道路", pinyin: "dào lù" }, { text: "吆喝", pinyin: "yāo he" }, { text: "烂泥塘", pinyin: "làn ní táng" }, { text: "舒服", pinyin: "shū fu" }] },
      s2_lesson26: { name: "第22课 小毛虫", words: [{ text: "毛虫", pinyin: "máo chóng" }, { text: "叶子", pinyin: "yè zi" }, { text: "目光", pinyin: "mù guāng" }, { text: "周游", pinyin: "zhōu yóu" }, { text: "纺织", pinyin: "fǎng zhī" }, { text: "编织", pinyin: "biān zhī" }, { text: "怎样", pinyin: "zěn yàng" }, { text: "声音", pinyin: "shēng yīn" }, { text: "花纹", pinyin: "huā wén" }, { text: "消失", pinyin: "xiāo shī" }, { text: "可怜", pinyin: "kě lián" }, { text: "挪动", pinyin: "nuó dòng" }, { text: "尽心竭力", pinyin: "jìn xīn jié lì" }, { text: "与世隔绝", pinyin: "yǔ shì gé jué" }] },
      s2_lesson27: { name: "第23课 祖先的摇篮", words: [{ text: "祖先", pinyin: "zǔ xiān" }, { text: "原始", pinyin: "yuán shǐ" }, { text: "意思", pinyin: "yì si" }, { text: "浓绿", pinyin: "nóng lǜ" }, { text: "一望无际", pinyin: "yí wàng wú jì" }, { text: "蓝天", pinyin: "lán tiān" }, { text: "野果", pinyin: "yě guǒ" }, { text: "野兔", pinyin: "yě tù" }, { text: "赛跑", pinyin: "sài pǎo" }, { text: "回忆", pinyin: "huí yì" }, { text: "摘野果", pinyin: "zhāi yě guǒ" }, { text: "逗小松鼠", pinyin: "dòu xiǎo sōng shǔ" }] },
      s2_lesson28: { name: "第24课 当世界年纪还小的时候", words: [{ text: "世界", pinyin: "shì jiè" }, { text: "学习", pinyin: "xué xí" }, { text: "成功", pinyin: "chéng gōng" }, { text: "月亮", pinyin: "yuè liang" }, { text: "主意", pinyin: "zhǔ yì" }, { text: "一直", pinyin: "yì zhí" }, { text: "只好", pinyin: "zhǐ hǎo" }, { text: "反复", pinyin: "fǎn fù" }, { text: "变化", pinyin: "biàn huà" }, { text: "方式", pinyin: "fāng shì" }, { text: "简单", pinyin: "jiǎn dān" }, { text: "自由", pinyin: "zì yóu" }, { text: "生长", pinyin: "shēng zhǎng" }, { text: "泥土", pinyin: "ní tǔ" }] },
      s2_lesson29: { name: "第25课 羿射九日", words: [{ text: "光明", pinyin: "guāng míng" }, { text: "觉得", pinyin: "jué de" }, { text: "值日", pinyin: "zhí rì" }, { text: "火球", pinyin: "huǒ qiú" }, { text: "沙石", pinyin: "shā shí" }, { text: "人类", pinyin: "rén lèi" }, { text: "艰难", pinyin: "jiān nán" }, { text: "决心", pinyin: "jué xīn" }, { text: "炎热", pinyin: "yán rè" }, { text: "害怕", pinyin: "hài pà" }, { text: "从此", pinyin: "cóng cǐ" }, { text: "重新", pinyin: "chóng xīn" }, { text: "生机", pinyin: "shēng jī" }, { text: "拉开", pinyin: "lā kāi" }, { text: "神箭手", pinyin: "shén jiàn shǒu" }, { text: "滋润", pinyin: "zī rùn" }] }
    }
  }
};

async function importVocab() {
  const baseUrl = 'http://localhost:3000';
  let count = 0;

  console.log('开始导入二年级下册词库...\n');

  for (const [subject, grades] of Object.entries(VOCAB_SEMESTER2)) {
    for (const [grade, lessons] of Object.entries(grades)) {
      for (const [key, lesson] of Object.entries(lessons)) {
        try {
          const res = await fetch(`${baseUrl}/api/builtin/${subject}/${grade}/${key}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              name: lesson.name,
              vocabType: lesson.vocabType || 'word',
              words: lesson.words,
              knowledgePoints: []
            })
          });
          if (res.ok) {
            console.log(`✓ ${lesson.name}`);
            count++;
          } else {
            console.log(`✗ ${lesson.name}: ${res.status}`);
          }
        } catch (e) {
          console.log(`✗ ${lesson.name}: ${e.message}`);
        }
      }
    }
  }

  console.log(`\n导入完成！共 ${count} 课`);
  console.log('刷新页面即可看到课文列表');
}

importVocab();
